
- hosts: localhost
  tasks:

  - name: Install Fedora packages
    dnf: name={{ item }}
    with_items:
      - git-core
      - make
      - python-devel
      - python-pip
      - python-psycopg2
      - openssl-devel
      - libselinux-python

  - name: Install nodejs and postgresql
    dnf: name={{ item }}
    with_items:
      - nodejs
      - postgresql
      - postgresql-devel
      - postgresql-contrib
      - postgresql-server

  - name: Initiate database
    command: service postgresql initdb
             creates=/var/lib/pgsql/data/postgresql.conf

  - name: Start PostgreSQL and enable at boot
    service: name=postgresql
             enabled=yes
             state=started

  - name: Ensure PostgreSQL is listening on all localhost
    lineinfile: dest=/var/lib/pgsql/data/postgresql.conf
                regexp='^#?listen_addresses\s*='
                line="listen_addresses = '127.0.0.1'"
                state=present
    notify: restart postgresql

  - lineinfile: dest=/var/lib/pgsql/data/pg_hba.conf
                regexp='host\s+all\s+all\s+127.0.0.1/32\s+md5'
                line='host all all 127.0.0.1/32 md5'
                insertbefore=BOF
    notify: restart postgresql

  - name: Give the vagrant user permission to database
    postgresql_user: name=vagrant role_attr_flags=SUPERUSER
    become: yes
    become_user: postgres

  - name: Upgrade virtualenv to latest version
    shell: '[ -x /usr/local/bin/virtualenv ] || pip install -U virtualenv'

  - name: Install app dependencies in a virtualenv
    pip:
      requirements=/vagrant/requirements/dev.txt
      virtualenv=/home/vagrant
      extra_args='--trusted-host dist.pinaxproject.com'
    become: yes
    become_user: vagrant

  - name: Make "vagrant" shell auto-activate the virtual environment
    lineinfile:
      dest=/home/vagrant/.bashrc
      line='source $HOME/bin/activate'

  - name: Copy settings file
    copy:
      src=/vagrant/pycon/settings/local.py-example
      dest=/vagrant/pycon/settings/local.py
      owner=vagrant group=vagrant

  - name: Activate developer settings
    lineinfile:
      dest=/vagrant/pycon/settings/local.py
      regexp='^#from .dev'
      line='from .dev import *'

  - name: Install an ancient version of the LESS compiler for CSS
    command: npm install -g less@1.3.3

  - name: Supply an informative message of the day
    copy: src=/vagrant/develop/motd dest=/etc/motd

  - name: Make psql willing to print UTF-8 strings
    copy: src=/vagrant/develop/dot-psqlrc dest=/home/vagrant/.psqlrc owner=vagrant

  - name: Create pycon-prod database role to avoid errors during prod import
    become: yes
    become_user: postgres
    postgresql_user: db=template1 name=pycon-prod

  - name: Create application database "pycon"
    become: yes
    become_user: postgres
    register: database_creation
    postgresql_db: name=pycon
                   encoding=UTF8
                   lc_collate=en_US.UTF-8
                   lc_ctype=en_US.UTF-8
                   template=template0

  - name: Migrate the application database if we just created it
    become: yes
    become_user: vagrant
    when: database_creation | changed
    shell: /home/vagrant/bin/python manage.py migrate
           chdir=/vagrant

  - name: Load database data from fixtures if we just created it
    become: yes
    become_user: vagrant
    when: database_creation | changed
    shell: /home/vagrant/bin/python manage.py loaddata fixtures/*
           chdir=/vagrant

  - name: Make bash history more sane
    lineinfile:
      dest: /home/vagrant/.bashrc
      line: 'HISTCONTROL=erasedups; unset HISTFILE'

  handlers:
  - name: restart postgresql
    service: name=postgresql state=restarted
